spring:
  jpa:
    show-sql: false
  flyway:
    enabled: true

logging:
  level:
    com.evantra: INFO
    org.springframework.security: WARN

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never