spring:
  main:
    allow-circular-references: true

  application:
    name: eventra

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.odtxiqvepwoegexjduey
    password: k68oV9RmU8tMel7V
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    root: INFO
    com.eventra: DEBUG
    org.hibernate: WARN

app:
  jwt:
    secret: xK9mP2qR5tY8uI3oL7vB4nM1cZ6jF0eW2aX5sD8gJ1kL4
    access-token-expiry: 900000
    refresh-token-expiry: 604800000

google:
  maps:
    api-key: AIzaSyA46QK2NAgB1f1XMSQ34d0ESeYCE2_1RNY