spring:
  main:
    allow-circular-references: true

  application:
    name: eventra

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    root: INFO
    com.eventra: DEBUG
    org.hibernate: WARN

app:
  jwt:
    secret: ${JWT_SECRET:tempSecretKeyForRenderAtLeast32Chars}
    access-token-expiry: 900000
    refresh-token-expiry: 604800000

google:
  maps:
    api-key: ${MAPS_API_KEY:}

---
---
---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    jdbc-url: jdbc:postgresql://postgres.lhqliiutgokossuzdzkn:${DB_PASSWORD}@aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET}