spring:
  application:
    name: eventra
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    root: INFO
    com.eventra: DEBUG
    org.hibernate: WARN

app:
  jwt:
    secret: ${JWT_SECRET:tempSecretKeyForRenderAtLeast32Chars}
    access-token-expiry: 900000
    refresh-token-expiry: 604800000

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.lhqliiutgokossuzdzkn
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET}